 /*
 * text-effect-autocorrection
 * docs https://docs.wtsolutions.cn
 * Souce code https://github.com/he-yang/text-effect-autocorrection
 *
 * Copyright (c) 2016 He Yang <he.yang @ wtsolutions.cn>
 * Licensed under the MIT license
 */


var databases={
		standard:[
			{ "s1": "[0-9][xX][0-9]","s1Opt":{ "matchWildCards": true }, "s2":"[xX]","s2Opt":{ "matchWildCards": true },"to": "×"},
			{ "s1": "Microsoft excel", "s1Opt":{}, "to": "Microsoft Excel"},			
			{ "s1": "[lL][*xX][bB]", "s1Opt":{ "matchWildCards": true }, "s2": "[*xX]" , "s2Opt":{ "matchWildCards": true }, "to": "×"},
			{ "s1": "[bB][*xX][hH]", "s1Opt":{ "matchWildCards": true }, "s2": "[*xX]" , "s2Opt":{ "matchWildCards": true }, "to": "×"},
		],
        /*
        extraLineBreaks:[
            {"s1": "^p^p^p^p^p^p^p^p^p^p","s1Opt":{},"to":"$paragraphLineBreak"},
            {"s1": "^p^p^p^p^p^p^p^p^p","s1Opt":{},"to":"$paragraphLineBreak"},
            {"s1": "^p^p^p^p^p^p^p^p","s1Opt":{},"to":"$paragraphLineBreak"},
            {"s1": "^p^p^p^p^p^p^p","s1Opt":{},"to":"$paragraphLineBreak"},
            {"s1": "^p^p^p^p^p^p","s1Opt":{},"to":"$paragraphLineBreak"},
            {"s1": "^p^p^p^p^p","s1Opt":{},"to":"$paragraphLineBreak"},
            {"s1": "^p^p^p^p","s1Opt":{},"to":"$paragraphLineBreak"},
            {"s1": "^p^p^p","s1Opt":{},"to":"$paragraphLineBreak"},
            {"s1": "^p^p","s1Opt":{},"to":"$paragraphLineBreak"}
        ],*/
		unit:[
            { "s1": "[0-9][mM][gG]/[lL]","s1Opt":{ "matchWildCards": true }, "s2":"mg/L","s2Opt":{}, "to":"mg/L"},
            { "s1": "[0-9] [mM][gG]/[lL]","s1Opt":{ "matchWildCards": true }, "s2":"mg/L","s2Opt":{}, "to":"mg/L"},
            { "s1": "[0-9][kK][wW]","s1Opt":{ "matchWildCards": true }, "s2":"kw","s2Opt":{}, "to": "kW"},
            { "s1": "[0-9] [kK][wW]","s1Opt":{ "matchWildCards": true }, "s2":"kw","s2Opt":{}, "to": "kW"},
            { "s1": "[0-9][kK][nN]","s1Opt":{ "matchWildCards": true }, "s2":"kn","s2Opt":{}, "to": "kN"},
            { "s1": "[0-9][kK][nN]","s1Opt":{ "matchWildCards": true }, "s2":"kn","s2Opt":{}, "to": "kN"},
            { "s1": "[0-9] [kK][nN]","s1Opt":{ "matchWildCards": true }, "s2":"kn","s2Opt":{}, "to": "kN"},
            { "s1": "[0-9][hH][aA]","s1Opt":{ "matchWildCards": true }, "s2":"ha","s2Opt":{}, "to": "ha"},
            { "s1": "[0-9] [hH][aA]","s1Opt":{ "matchWildCards": true }, "s2":"ha","s2Opt":{}, "to": "ha"},
            { "s1": "[0-9][mM][pP][aA]","s1Opt":{ "matchWildCards": true }, "s2":"mpa","s2Opt":{}, "to": "MPa"},          { "s1": "[0-9] [mM][pP][aA]","s1Opt":{ "matchWildCards": true }, "s2":"mpa","s2Opt":{}, "to": "MPa"},         { "s1": "[0-9][mM][lL]","s1Opt":{ "matchWildCards": true }, "s2":"ml","s2Opt":{}, "to": "mL"},
            { "s1": "[0-9] [mM][lL]","s1Opt":{ "matchWildCards": true }, "s2":"ml","s2Opt":{}, "to": "mL"},
			{ "s1": "[0-9]kvar","s1Opt":{ "matchWildCards": true }, "s2": "kvar","s2Opt":{}, "to": "kvar"},			
            { "s1": "[0-9] kvar","s1Opt":{ "matchWildCards": true }, "s2": "kvar","s2Opt":{}, "to": "kvar"},			
            { "s1": "[0-9]kva[!r]","s1Opt":{ "matchWildCards": true }, "s2": "kva","s2Opt":{}, "to": "kVA"},			
            { "s1": "[0-9] kva[!r]","s1Opt":{ "matchWildCards": true }, "s2": "kva","s2Opt":{}, "to": "kVA"},

            { "s1": "[mM][23]","s1Opt":{ "matchWildCards": true }, "s2": "[23]","s2Opt":{ "matchWildCards": true }, "to": "$superscript"},
            { "s1": "[mM]3/[aAdDhHsS]","s1Opt":{ "matchWildCards": true }, "s2": "3","s2Opt":{ "matchWildCards": true }, "to": "$superscript"},
            { "s1": "[mM]3/[aAdDhHsS]","s1Opt":{ "matchWildCards": true }, "s2": "[ADHSM]","s2Opt":{ "matchWildCards": true }, "to": "$lowercase"},			
            { "s1": "kg/m[2-3]","s1Opt":{ "matchWildCards": true }, "s2": "[2-3]","s2Opt":{ "matchWildCards": true }, "to": "$superscript"},			
            { "s1": "kg/cm[2-3]","s1Opt":{ "matchWildCards": true }, "s2": "[2-3]","s2Opt":{ "matchWildCards": true }, "to": "$superscript"},
            { "s1": "miles2","s1Opt":{}, "s2": "2","s2Opt":{}, "to": "$superscript"},			
            { "s1": "g/cm3","s1Opt":{}, "s2": "3","s2Opt":{}, "to": "$superscript"},		
            { "s1": "m2/s","s1Opt":{}, "s2": "2","s2Opt":{}, "to": "$superscript"},
            { "s1": "in[2-3]","s1Opt":{ "matchWildCards": true }, "s2": "[2-3]","s2Opt":{ "matchWildCards": true }, "to": "$superscript"},
            { "s1": "ft[2-3]","s1Opt":{ "matchWildCards": true }, "s2": "[2-3]","s2Opt":{ "matchWildCards": true }, "to": "$superscript"},
            { "s1": "yd[2-3]","s1Opt":{ "matchWildCards": true }, "s2": "[2-3]","s2Opt":{ "matchWildCards": true }, "to": "$superscript"},

            { "s1": "kw.h","s1Opt":{}, "s2": ".","s2Opt":{}, "to": "·"},
            { "s1": "kw.h","s1Opt":{}, "s2": "w","s2Opt":{}, "to": "W"},
            { "s1": "n.m","s1Opt":{}, "s2": "n","s2Opt":{}, "to": "N"},
            { "s1": "n.m","s1Opt":{}, "s2": ".","s2Opt":{}, "to": "·"},
            { "s1": "pa.s","s1Opt":{}, "s2": ".","s2Opt":{}, "to": "·"},
            { "s1": "pa.s","s1Opt":{}, "s2": "p","s2Opt":{}, "to": "P"},
            {"s1": "L/m2[`.]s", "s1Opt":{ "matchWildCards": true },"s2": "2" ,"s2Opt":{},"to": "$superscript"},
            {"s1": "L/m2[`.]s", "s1Opt":{ "matchWildCards": true },"s2": "[`.]" ,"s2Opt":{ "matchWildCards": true },"to": "·"},

			{ "s1": "(mg/l)", "s1Opt":{}, "to": "(mg/L)"},
			{ "s1": "(kw)", "s1Opt":{}, "to": "(kW)"},
			{ "s1": "(kn)", "s1Opt":{}, "to": "(kN)"},
			{ "s1": "(ha)", "s1Opt":{}, "to": "(ha)"},
			{ "s1": "(mpa)", "s1Opt":{}, "to": "(MPa)"},
			{ "s1": "(ml)", "s1Opt":{}, "to": "(mL)"},
			{ "s1": "db(A)", "s1Opt":{}, "to": "dB(A)"},
			{ "s1": "(kn/m)", "s1Opt":{}, "to": "(kN/m)"},
			{ "s1": "(kvar)", "s1Opt":{}, "to": "(kvar)"},
			{ "s1": "(kva)", "s1Opt":{}, "to": "(kVA)"}
            			
		],
		chemical:[
            { "s1": "[hH]2[oOsS]","s1Opt":{ "matchWildCards": true }, "s2": "2","s2Opt":{}, "to": "$subscript"},
            { "s1": "NH3","s1Opt":{}, "s2": "3","s2Opt":{}, "to": "$subscript"},
            { "s1": "PO43-","s1Opt":{}, "s2": "4","s2Opt":{}, "to": "$subscript"},
            { "s1": "PO43-","s1Opt":{}, "s2": "3-","s2Opt":{}, "to": "$superscript"},
            { "s1": "SO42-","s1Opt":{}, "s2": "4","s2Opt":{}, "to": "$subscript"},
            { "s1": "SO42-","s1Opt":{}, "s2": "2-","s2Opt":{}, "to": "$superscript"},
            { "s1": "Ca2+","s1Opt":{}, "s2": "2+","s2Opt":{}, "to": "$superscript"},
            { "s1": "Mg2+","s1Opt":{}, "s2": "2+","s2Opt":{}, "to": "$superscript"},
            { "s1": "F-","s1Opt":{}, "s2": "-","s2Opt":{}, "to": "$superscript"},
            { "s1": "Cl-","s1Opt":{}, "s2": "-","s2Opt":{}, "to": "$superscript"},
            { "s1": "KMnO4","s1Opt":{}, "s2": "4","s2Opt":{}, "to": "$subscript"},
            { "s1": "CaCO3","s1Opt":{}, "s2": "3","s2Opt":{}, "to": "$subscript"},
            { "s1": "Al2O3","s1Opt":{}, "s2": "[2-3]","s2Opt":{ "matchWildCards": true }, "to": "$subscript"},
            { "s1": "NaClO[2-3]", "s1Opt":{ "matchWildCards": true },"s2": "[2-3]","s2Opt":{ "matchWildCards": true }, "to": "$subscript"},
            { "s1": "[hH]2[cCnNsS][oO][3-4]", "s1Opt":{ "matchWildCards": true },"s2": "[2-4]","s2Opt":{ "matchWildCards": true }, "to": "$subscript"},
            { "s1": "Fe[2-3]O[3-4]", "s1Opt":{ "matchWildCards": true },"s2": "[2-4]","s2Opt":{ "matchWildCards": true }, "to": "$subscript"},
            { "s1": "FeCl[2-3]", "s1Opt":{ "matchWildCards": true },"s2": "[2-3]","s2Opt":{ "matchWildCards": true }, "to": "$subscript"},            
            { "s1": "H2O","s1Opt":{},"to":"H2O"},
            { "s1": "H2O","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe2O3","s1Opt":{},"to":"Fe2O3"},
            { "s1": "Fe2O3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe2O3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Cu2(OH)2CO3","s1Opt":{},"to":"Cu2(OH)2CO3"},
            { "s1": "Cu2(OH)2CO3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Cu2(OH)2CO3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Cu2(OH)2CO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "C2H5OH","s1Opt":{},"to":"C2H5OH"},
            { "s1": "C2H5OH","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "C2H5OH","s1Opt":{},"s2":"5","s2Opt":{},"to":"$subscript"},
            { "s1": "CH3OH","s1Opt":{},"to":"CH3OH"},
            { "s1": "CH3OH","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "CH3COOH","s1Opt":{},"to":"CH3COOH"},
            { "s1": "CH3COOH","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Na2CO3","s1Opt":{},"to":"Na2CO3"},
            { "s1": "Na2CO3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Na2CO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "CuSO4","s1Opt":{},"to":"CuSO4"},
            { "s1": "CuSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "FeSO4","s1Opt":{},"to":"FeSO4"},
            { "s1": "FeSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "CaCl2","s1Opt":{},"to":"CaCl2"},
            { "s1": "CaCl2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "CaSO4","s1Opt":{},"to":"CaSO4"},
            { "s1": "CaSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "Na2S","s1Opt":{},"to":"Na2S"},
            { "s1": "Na2S","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            {"s1":"<[oOnNhH]2>","s1Opt":{"matchWildCards":true},"s2":"[onh]","s2Opt":{"matchWildCards":true},"to":"$uppercase"},
            {"s1":"<[oOnNhH]2>","s1Opt":{"matchWildCards":true},"s2":"2","s2Opt":{},"to":"$subscript"},
            {"s1":"[!a-zA-Z][oOnNhH]2[!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"[onh]","s2Opt":{"matchWildCards":true},"to":"$uppercase"},
            {"s1":"[!a-zA-Z][oOnNhH]2[!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"2","s2Opt":{},"to":"$subscript"},   
            { "s1": "Cl2","s1Opt":{},"to":"Cl2"},
            { "s1": "Cl2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "NH3","s1Opt":{},"to":"NH3"},
            { "s1": "NH3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "CO2","s1Opt":{},"to":"CO2"},
            { "s1": "CO2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "SO2","s1Opt":{},"to":"SO2"},
            { "s1": "SO2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "SO3","s1Opt":{},"to":"SO3"},
            { "s1": "SO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "NO2","s1Opt":{},"to":"NO2"},
            { "s1": "NO2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "CH4","s1Opt":{},"to":"CH4"},
            { "s1": "CH4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "C2H2","s1Opt":{},"to":"C2H2"},
            { "s1": "C2H2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "C2H2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "MnO2","s1Opt":{},"to":"MnO2"},
            { "s1": "MnO2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Al2O3","s1Opt":{},"to":"Al2O3"},
            { "s1": "Al2O3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Al2O3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe2O3","s1Opt":{},"to":"Fe2O3"},
            { "s1": "Fe2O3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe2O3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe3O4","s1Opt":{},"to":"Fe3O4"},
            { "s1": "Fe3O4","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe3O4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "P2O5","s1Opt":{},"to":"P2O5"},
            { "s1": "P2O5","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "P2O5","s1Opt":{},"s2":"5","s2Opt":{},"to":"$subscript"},
            { "s1": "WO3","s1Opt":{},"to":"WO3"},
            { "s1": "WO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "H2O2","s1Opt":{},"to":"H2O2"},
            { "s1": "H2O2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "H2O2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "HNO3","s1Opt":{},"to":"HNO3"},
            { "s1": "HNO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "H2SO4","s1Opt":{},"to":"H2SO4"},
            { "s1": "H2SO4","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "H2SO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "H3PO4","s1Opt":{},"to":"H3PO4"},
            { "s1": "H3PO4","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "H3PO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "H2CO3","s1Opt":{},"to":"H2CO3"},
            { "s1": "H2CO3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "H2CO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "H2S","s1Opt":{},"to":"H2S"},
            { "s1": "H2S","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Ca(OH)2","s1Opt":{},"to":"Ca(OH)2"},
            { "s1": "Ca(OH)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Mg(OH)2","s1Opt":{},"to":"Mg(OH)2"},
            { "s1": "Mg(OH)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Al(OH)3","s1Opt":{},"to":"Al(OH)3"},
            { "s1": "Al(OH)3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe(OH)3","s1Opt":{},"to":"Fe(OH)3"},
            { "s1": "Fe(OH)3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe(OH)2","s1Opt":{},"to":"Fe(OH)2"},
            { "s1": "Fe(OH)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Cu(OH)2","s1Opt":{},"to":"Cu(OH)2"},
            { "s1": "Cu(OH)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Ba(OH)2","s1Opt":{},"to":"Ba(OH)2"},
            { "s1": "Ba(OH)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "K2SO4","s1Opt":{},"to":"K2SO4"},
            { "s1": "K2SO4","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "K2SO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "KHSO4","s1Opt":{},"to":"KHSO4"},
            { "s1": "KHSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "Na2SO4","s1Opt":{},"to":"Na2SO4"},
            { "s1": "Na2SO4","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Na2SO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "Na2SO3","s1Opt":{},"to":"Na2SO3"},
            { "s1": "Na2SO3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Na2SO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "NaHSO4","s1Opt":{},"to":"NaHSO4"},
            { "s1": "NaHSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "MgSO4","s1Opt":{},"to":"MgSO4"},
            { "s1": "MgSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "Al2(SO4)3","s1Opt":{},"to":"Al2(SO4)3"},
            { "s1": "Al2(SO4)3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Al2(SO4)3","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "Al2(SO4)3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe2(SO4)3","s1Opt":{},"to":"Fe2(SO4)3"},
            { "s1": "Fe2(SO4)3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe2(SO4)3","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe2(SO4)3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "FeSO4","s1Opt":{},"to":"FeSO4"},
            { "s1": "FeSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "ZnSO4","s1Opt":{},"to":"ZnSO4"},
            { "s1": "ZnSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "CuSO4","s1Opt":{},"to":"CuSO4"},
            { "s1": "CuSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "BaSO4","s1Opt":{},"to":"BaSO4"},
            { "s1": "BaSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "CaCO3","s1Opt":{},"to":"CaCO3"},
            { "s1": "CaCO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            //{ "s1": "Na2CO3","s1Opt":{},"to":"Na2CO3"},
            //{ "s1": "Na2CO3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            //{ "s1": "Na2CO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "NaHCO3","s1Opt":{},"to":"NaHCO3"},
            { "s1": "NaHCO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "ZnCl2","s1Opt":{},"to":"ZnCl2"},
            { "s1": "ZnCl2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "FeCl3","s1Opt":{},"to":"FeCl3"},
            { "s1": "FeCl3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "FeCl2","s1Opt":{},"to":"FeCl2"},
            { "s1": "FeCl2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "CuCl2","s1Opt":{},"to":"CuCl2"},
            { "s1": "CuCl2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "BaCl2","s1Opt":{},"to":"BaCl2"},
            { "s1": "BaCl2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "KNO3","s1Opt":{},"to":"KNO3"},
            { "s1": "KNO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "NaNO3","s1Opt":{},"to":"NaNO3"},
            { "s1": "NaNO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Zn(NO3)2","s1Opt":{},"to":"Zn(NO3)2"},
            { "s1": "Zn(NO3)2","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Zn(NO3)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Mg(NO3)2","s1Opt":{},"to":"Mg(NO3)2"},
            { "s1": "Mg(NO3)2","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Mg(NO3)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe(NO3)3","s1Opt":{},"to":"Fe(NO3)3"},
            { "s1": "Fe(NO3)3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe(NO3)3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Cu(NO3)2","s1Opt":{},"to":"Cu(NO3)2"},
            { "s1": "Cu(NO3)2","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Cu(NO3)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Hg(NO3)2","s1Opt":{},"to":"Hg(NO3)2"},
            { "s1": "Hg(NO3)2","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Hg(NO3)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "AgNO3","s1Opt":{},"to":"AgNO3"},
            { "s1": "AgNO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Ca(NO3)2","s1Opt":{},"to":"Ca(NO3)2"},
            { "s1": "Ca(NO3)2","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Ca(NO3)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "KMnO4","s1Opt":{},"to":"KMnO4"},
            { "s1": "KMnO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "KClO3","s1Opt":{},"to":"KClO3"},
            { "s1": "KClO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "K2MnO4","s1Opt":{},"to":"K2MnO4"},
            { "s1": "K2MnO4","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "K2MnO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "Ca(H2PO4)2","s1Opt":{},"to":"Ca(H2PO4)2"},
            { "s1": "Ca(H2PO4)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Ca(H2PO4)2","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "Ca(H2PO4)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "(NH4)2SO4","s1Opt":{},"to":"(NH4)2SO4"},
            { "s1": "(NH4)2SO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "(NH4)2SO4","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "(NH4)2SO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "NH4NO3","s1Opt":{},"to":"NH4NO3"},
            { "s1": "NH4NO3","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "NH4NO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "NH4HCO3","s1Opt":{},"to":"NH4HCO3"},
            { "s1": "NH4HCO3","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "NH4HCO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "NH4Cl","s1Opt":{},"to":"NH4Cl"},
            { "s1": "NH4Cl","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "NH3","s1Opt":{},"to":"NH3"},
            { "s1": "NH3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "CO(NH2)2","s1Opt":{},"to":"CO(NH2)2"},
            { "s1": "CO(NH2)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "CO(NH2)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Ca3(PO4)2","s1Opt":{},"to":"Ca3(PO4)2"},
            { "s1": "Ca3(PO4)2","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Ca3(PO4)2","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "Ca3(PO4)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "CaSO4","s1Opt":{},"to":"CaSO4"},
            { "s1": "CaSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "NH4H2PO4","s1Opt":{},"to":"NH4H2PO4"},
            { "s1": "NH4H2PO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "NH4H2PO4","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "NH4H2PO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "(NH4)2HPO4","s1Opt":{},"to":"(NH4)2HPO4"},
            { "s1": "(NH4)2HPO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "(NH4)2HPO4","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "(NH4)2HPO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "KH2PO4","s1Opt":{},"to":"KH2PO4"},
            { "s1": "KH2PO4","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "KH2PO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "ZnSO4","s1Opt":{},"to":"ZnSO4"},
            { "s1": "ZnSO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "Na2SO4","s1Opt":{},"to":"Na2SO4"},
            { "s1": "Na2SO4","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Na2SO4","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "KAl(SO4)2","s1Opt":{},"to":"KAl(SO4)2"},
            { "s1": "KAl(SO4)2","s1Opt":{},"s2":"4","s2Opt":{},"to":"$subscript"},
            { "s1": "KAl(SO4)2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "CaF2","s1Opt":{},"to":"CaF2"},
            { "s1": "CaF2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "CuFeS2","s1Opt":{},"to":"CuFeS2"},
            { "s1": "CuFeS2","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Al2O3","s1Opt":{},"to":"Al2O3"},
            { "s1": "Al2O3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Al2O3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe2CO3","s1Opt":{},"to":"Fe2CO3"},
            { "s1": "Fe2CO3","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"},
            { "s1": "Fe2CO3","s1Opt":{},"s2":"3","s2Opt":{},"to":"$subscript"},
            { "s1": "Na2O","s1Opt":{},"to":"Na2O"},
            { "s1": "Na2O","s1Opt":{},"s2":"2","s2Opt":{},"to":"$subscript"}
		],
        alkanes:[
            {"s1":"<[cC][0-9]{1,2}[hH][0-9]{1,2}>","s1Opt":{"matchWildCards":true},"s2":"c","s2Opt":{},"to":"C"},
            {"s1":"<[cC][0-9]{1,2}[hH][0-9]{1,2}>","s1Opt":{"matchWildCards":true},"s2":"h","s2Opt":{},"to":"H"},
            {"s1":"<[cC][0-9]{1,2}[hH][0-9]{1,2}>","s1Opt":{"matchWildCards":true},"s2":"[0-9]","s2Opt":{"matchWildCards":true},"to":"$subscript"},
            {"s1":"[!a-zA-Z][cC][0-9]{1,2}[hH][0-9]{1,2}[!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"c","s2Opt":{"matchWildCards":true},"to":"C"},
            {"s1":"[!a-zA-Z][cC][0-9]{1,2}[hH][0-9]{1,2}[!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"h","s2Opt":{"matchWildCards":true},"to":"H"},
            {"s1":"[!a-zA-Z][cC][0-9]{1,2}[hH][0-9]{1,2}[!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"[0-9]","s2Opt":{"matchWildCards":true},"to":"$subscript"}
        ],
		water:[
            { "s1": "[dD][nN][0-9]","s1Opt":{ "matchWildCards": true }, "s2":"dn","s2Opt":{},"to": "DN"},
            { "s1": "[dD][eE][0-9]","s1Opt":{ "matchWildCards": true }, "s2":"de","s2Opt":{},"to": "de"},
			{ "s1": "[pP][hH] [0-9]","s1Opt":{ "matchWildCards": true }, "s2":"ph","s2Opt":{},"to": "pH"},
			{ "s1": "[pP][hH][0-9]","s1Opt":{ "matchWildCards": true }, "s2":"ph","s2Opt":{},"to": "pH"},
			{ "s1": "CODMn","s1Opt":{}, "s2": "Mn","s2Opt":{}, "to": "$subscript"},
			{ "s1": "CODMn","s1Opt":{}, "s2": "cod","s2Opt":{}, "to": "COD"},
            { "s1": "CODCr","s1Opt":{}, "s2": "Cr","s2Opt":{}, "to": "$subscript"},
            { "s1": "CODCr","s1Opt":{}, "s2": "cod","s2Opt":{}, "to": "COD"},
            { "s1": "ntu","s1Opt":{}, "to": "NTU"},	
            { "s1": "BOD5","s1Opt":{}, "s2": "bod","s2Opt":{}, "to": "BOD"},		            
            { "s1": "BOD5","s1Opt":{}, "s2": "5","s2Opt":{}, "to": "$subscript"},
            { "s1": "A2O","s1Opt":{}, "s2": "2","s2Opt":{}, "to": "$superscript"},
            { "s1": "A2O","s1Opt":{}, "s2": "[ao]","s2Opt":{"matchWildCards": true}, "to": "$uppercase"},
        ],
        environment:[
            {"s1":"[!a-zA-Z][pP][hH][!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"ph","s2Opt":{},"to":"pH"},
            {"s1":"<[pP][hH]>","s1Opt":{"matchWildCards":true},"to":"pH"},{"s1":"<[nN][hH]3[-^=—][nN]>","s1Opt":{"matchWildCards":true},"to":"NH3–N"},
            {"s1":"<[nN][hH]3[-^=—][nN]>","s1Opt":{"matchWildCards":true},"s2":"3","s2Opt":{},"to":"$subscript"},
            {"s1":"[!a-zA-Z][nN][hH]3[-^=—][nN][!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"[nN][hH]3[-^=—][nN]","s2Opt":{"matchWildCards":true},"to":"NH3–N"},
            {"s1":"[!a-zA-Z][nN][hH]3[-^=—][nN][!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"3","s2Opt":{},"to":"$subscript"},
            {"s1":"<[nN][oO][xX]>","s1Opt":{"matchWildCards":true},"to":"NOX"},
            {"s1":"<[nN][oO][xX]>","s1Opt":{"matchWildCards":true},"s2":"x","s2Opt":{},"to":"$subscript"},
            {"s1":"[!a-zA-Z][nN][oO][xX][!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"nox","s2Opt":{},"to":"NOX"},
            {"s1":"[!a-zA-Z][nN][oO][xX][!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"x","s2Opt":{},"to":"$subscript"},
            {"s1":"[!a-zA-Z][nN][oO][!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"no","s2Opt":{},"to":"NO"},
            {"s1":"<[nN][oO]>","s1Opt":{"matchWildCards":true},"to":"NO"},
            {"s1":"[!a-zA-Z][bB][oO][dD][!a-zA-Z]","s1Opt":{"matchWildCards":true},"s2":"bod","s2Opt":{},"to":"BOD"},
            {"s1":"<[bB][oO][dD]>","s1Opt":{"matchWildCards":true},"to":"BOD"},
            {"s1":"pm10","s1Opt":{},"s2":"pm","s2Opt":{},"to":"PM"},{"s1":"pm10","s1Opt":{},"s2":"10","s2Opt":{},"to":"$subscript"},
            {"s1":"pm2.5","s1Opt":{},"s2":"pm","s2Opt":{},"to":"PM"},{"s1":"pm2.5","s1Opt":{},"s2":"2.5","s2Opt":{},"to":"$subscript"}
        ]
	}